travis:
  secure:
    BINSTAR_TOKEN: M4UHyDukOrTUOT6GJopwQW0cPvnREvSJbm30BAtarx4+T4DoUvQSQg2SZmisrmd6EGkzNUZNrSRDHLjPisn+QLy+S5dU8ebgjoiyM5F5ssIuEhdQzJPkdg2NX8z5PHv6hgopfvC5NYlz26rB/pLHtPo9zF7QELMkG7vqA8rZFCkHHP2IoJkcJ5FH+ycmplRwqa0lVhFuMXupzL1i8StQrvkwZI0pRpPvQN0dOUdB0+3m4c3dzwxHPcQ1Lt5uCBuKllawRHNNj4bPAUHkvl7TAFXXpKNfTb/LhEyrVPJD8P+mwntAtJ7hdNNIfjtcDxEKfDxRzcjT6NUR+kc1NvEaP8BB03SLcjOFvOaqIjsALjZiR85OA5rX0+pm2ychyj/9x+QBcwa7x06wpTNrHPlO57l+ZfreAmbtulYbVCTrG0tUmt9t7ytTvO3XrQgFqbW2SqF+I/cNeHhwyEXAGGo4AaO5M9V161o7Vg4gmM7v0Eask7wlmKLg0V25Ps8vYOd7CK/MAYapqIEWjKx7uKoohTblcUegTn/SLBKaJhKSNcpky0l8Y9Mrxd0SaN+JHvZNHgV4tMfrUGE9DL6wnkcj8veSjljx+xuiOAFxjzy/HjMFidmmxv4NMBR0nfb2xgmQRBMmytH3meiRArfPc4XHIT68K9DN3N9IO9JqkS+/1kM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
